# NumPy基础：数组与矢量计算

In [1]:
%matplotlib inline

In [2]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## NumPy的ndarray：一种多维的数组对象

In [3]:
data = randn(2, 3)

In [4]:
data

array([[-0.1207,  0.0896,  1.4398],
       [ 2.0725,  1.2341,  0.1871]])

In [5]:
data * 10

array([[ -1.207 ,   0.8958,  14.3982],
       [ 20.7252,  12.3411,   1.8708]])

In [6]:
data + data

array([[-0.2414,  0.1792,  2.8796],
       [ 4.145 ,  2.4682,  0.3742]])

In [8]:
data.shape

(2L, 3L)

In [9]:
data.dtype

dtype('float64')

### 创建ndarray

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [12]:
# -*- coding: utf-8 -*-
# 嵌套序列转换成多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.shape

(2L, 4L)

In [20]:
# -*- coding: utf-8 -*-
# ndarray会推断出合适的数据类型
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int32')

In [21]:
# -*- coding: utf-8 -*-
# 创建特殊的ndarray对象

In [22]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [23]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [24]:
np.ones((3, 6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [25]:
np.empty((2, 3, 2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

### ndarray的数据类型

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([ 1.,  2.,  3.])

In [30]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3])

In [31]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [32]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [33]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [34]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [35]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [36]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)