### 1.4.4 学习`Numpy`

In [12]:
import numpy
numpy.__version__

'1.12.1'

In [13]:
import numpy as np

In [14]:
a = np.array([0, 1, 2, 3, 4, 5])
a

array([0, 1, 2, 3, 4, 5])

In [16]:
a.ndim

1

In [18]:
a.shape

(6L,)

In [19]:
b = a.reshape((3, 2))  # 此时b是嵌套的数组
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
b.ndim

2

In [21]:
b.shape

(3L, 2L)

In [22]:
b[1][0] = 77
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [23]:
a  # 注意，此时a已经变了， 所以需要copy

array([ 0,  1, 77,  3,  4,  5])

In [24]:
c = a.reshape((3, 2)).copy()
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [25]:
c[0][0] = -99
c

array([[-99,   1],
       [ 77,   3],
       [  4,   5]])

In [26]:
a

array([ 0,  1, 77,  3,  4,  5])

---------------------

In [27]:
[1, 2, 3] *5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [28]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [29]:
d*5

array([ 5, 10, 15])

In [30]:
e = np.array([3, 2, 1])
e+d

array([4, 4, 4])

#### 1. 索引

In [31]:
a

array([ 0,  1, 77,  3,  4,  5])

In [32]:
a[np.array([1 ,2, 3])]

array([ 1, 77,  3])

In [35]:
a[[1,2,3]]

array([ 1, 77,  3])

In [36]:
a[a>4]

array([77,  5])

In [37]:
a[a>4]=4

In [38]:
a

array([0, 1, 4, 3, 4, 4])

In [39]:
b

array([[0, 1],
       [4, 3],
       [4, 4]])

In [40]:
c

array([[-99,   1],
       [ 77,   3],
       [  4,   5]])

In [42]:
c.clip(0, 4)  # 修剪函数

array([[0, 1],
       [4, 3],
       [4, 4]])

#### 2. 处理不存在的值

In [43]:
c = np.array([1, 2, np.NAN, 3, 4])
c

array([  1.,   2.,  nan,   3.,   4.])

In [44]:
np.isnan(c)

array([False, False,  True, False, False], dtype=bool)

In [45]:
c[~np.isnan(c)]

array([ 1.,  2.,  3.,  4.])

In [46]:
np.mean(c[~np.isnan(c)])

2.5

#### 3.运行时的比较

In [47]:
import timeit

normal_py_sec = timeit.timeit('sum(x*x for x in xrange(1000))',
                              number=10000)
naive_np_sec = timeit.timeit('sum(na*na)',
                             setup="import numpy as np; na=np.arange(1000)",
                             number=10000)
good_np_sec = timeit.timeit('na.dot(na)',
                            setup="import numpy as np; na=np.arange(1000)",
                            number=10000)

print("Normal Python: %f sec" % normal_py_sec)
print("Naive NumPy: %f sec" % naive_np_sec)
print("Good NumPy: %f sec" % good_np_sec)

Normal Python: 0.852278 sec
Naive NumPy: 1.146271 sec
Good NumPy: 0.018598 sec


----------------------------------